/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Petpulse.views;

import com.Petpulse.utils.StringUtils;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajeet
 */
public class Petpulse extends javax.swing.JFrame {
 int snumber;
    /**
     * Creates new form NewJFrame1
     */
    public Petpulse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetpulse = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jpanelAdd2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        tfTraits = new javax.swing.JTextField();
        tfOrigin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        tfSnumber = new javax.swing.JTextField();
        tfHealthProblem = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        tfBreed = new javax.swing.JTextField();
        btnAdd4 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        spinnerObey = new javax.swing.JSpinner();
        spinnerHeight1 = new javax.swing.JSpinner();
        spinnerLongevity2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        cbYellow = new javax.swing.JCheckBox();
        cbBlack = new javax.swing.JCheckBox();
        cbGolden = new javax.swing.JCheckBox();
        cbFawn = new javax.swing.JCheckBox();
        cbTan = new javax.swing.JCheckBox();
        cbChocolate = new javax.swing.JCheckBox();
        cbBlue = new javax.swing.JCheckBox();
        cbWhite = new javax.swing.JCheckBox();
        cbSesame = new javax.swing.JCheckBox();
        cbRed = new javax.swing.JCheckBox();
        spinnerHeight2 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        comboBox_Add = new javax.swing.JComboBox<>();
        spinnerLongevity1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JButton();
        tfTraits_Update = new javax.swing.JTextField();
        tfOrigin_Update = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfSnumber_Update = new javax.swing.JTextField();
        tfHealthProblem_Update = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tfBreed_Update = new javax.swing.JTextField();
        btnUpdate2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        spinnerObey_Update = new javax.swing.JSpinner();
        spinnerLongevity2_Update = new javax.swing.JSpinner();
        spinnerLongevity1_Update = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cbYellow_Update = new javax.swing.JCheckBox();
        cbBlack_Update = new javax.swing.JCheckBox();
        cbGolden_Update = new javax.swing.JCheckBox();
        cbFawn_Update = new javax.swing.JCheckBox();
        cbTan_Update = new javax.swing.JCheckBox();
        cbChocolate_Update = new javax.swing.JCheckBox();
        cbBlue_Update = new javax.swing.JCheckBox();
        cbWhite_Update = new javax.swing.JCheckBox();
        cbSesame_Update = new javax.swing.JCheckBox();
        cbRed_Update = new javax.swing.JCheckBox();
        comboBox_Update = new javax.swing.JComboBox<>();
        spinnerHeight1_Update = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spinnerHeight2_Update = new javax.swing.JSpinner();

        jLabel6.setText("TO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPetpulse.setBackground(new java.awt.Color(188, 210, 224));
        tblPetpulse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Labrodor Retriver", "Canada", "Yellow,Black,Chocolate", "21-24", "Blue", "10-12", "Friendly", "Obesity", "95"},
                {"2", "German Shepard", "Germany", "Black,Tan", "22-26", "Brown", "10-12", "Loyal", "Pancreatitis", "95"},
                {"3", "Akita", "Japan", "Red,Fawn,Sesame", "24-28", "Brown", "10-13", "Energetic", "Eye Problem", "50"},
                {"4", "Great Dane", "Germany", "Black,Blue,Fawn", "28-34", "Brown", "7-10", "Gentle", "Cancer", "50"},
                {"5", "Golden Retriver", "Scotland", "Gold", "21-24", "Brown", "10-13", "Good-natured", "Dental Problem", "95"},
                {"6", "Lhasa Apso", "Tibet", "Black,White", "10-11", "Brown", "12-14", "Playful", "Skin Allergies", "30"}
            },
            new String [] {
                "S.No", "Breed", "Country of Origin", "Fur Color", "Height(in)", "Eye Color", "Longevity(yrs)", "Character Traits", "Common Health Problems", "Obey%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPetpulse.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPetpulse);
        if (tblPetpulse.getColumnModel().getColumnCount() > 0) {
            tblPetpulse.getColumnModel().getColumn(0).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(1).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(2).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(4).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(6).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(7).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(8).setResizable(false);
            tblPetpulse.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(56, 38, 36));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Petpulse");

        jTextField1.setBackground(new java.awt.Color(255, 245, 224));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(173, 173, 173));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 245, 224));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(81, 81, 81)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel5.setBackground(new java.awt.Color(188, 210, 224));

        btnAdd.setBackground(new java.awt.Color(29, 57, 50));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(23, 35, 52));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(221, 55, 69));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel10.setBackground(new java.awt.Color(56, 38, 36));

        jpanelAdd2.setBackground(new java.awt.Color(188, 210, 224));
        jpanelAdd2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(60, 63, 61));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jpanelAdd2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 140, 30));

        tfTraits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTraitsActionPerformed(evt);
            }
        });
        jpanelAdd2.add(tfTraits, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 162, -1));

        tfOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOriginActionPerformed(evt);
            }
        });
        jpanelAdd2.add(tfOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 132, 162, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("S.No");
        jpanelAdd2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 57, 54, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("Longevity");
        jpanelAdd2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 70, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Common Health Problems");
        jpanelAdd2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 150, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Height (in)");
        jpanelAdd2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 178, 65, -1));

        tfSnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnumberActionPerformed(evt);
            }
        });
        jpanelAdd2.add(tfSnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 54, 162, -1));
        jpanelAdd2.add(tfHealthProblem, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 162, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Breed");
        jpanelAdd2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 95, 54, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Character Traits");
        jpanelAdd2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setText("Obey%");
        jpanelAdd2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 54, -1));
        jpanelAdd2.add(tfBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 92, 162, -1));

        btnAdd4.setBackground(new java.awt.Color(29, 57, 50));
        btnAdd4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd4.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd4.setText("ADD");
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });
        jpanelAdd2.add(btnAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 140, 29));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Eye Color");
        jpanelAdd2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 54, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Country of Origin");
        jpanelAdd2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 135, -1, -1));

        spinnerObey.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        jpanelAdd2.add(spinnerObey, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 162, -1));
        jpanelAdd2.add(spinnerHeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 72, -1));
        jpanelAdd2.add(spinnerLongevity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 73, -1));

        jLabel5.setText("TO");
        jpanelAdd2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Fur Color");
        jpanelAdd2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 70, -1));

        cbYellow.setText("Yellow");
        cbYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYellowActionPerformed(evt);
            }
        });
        jpanelAdd2.add(cbYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        cbBlack.setText("Black");
        jpanelAdd2.add(cbBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));

        cbGolden.setText("Golden");
        jpanelAdd2.add(cbGolden, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        cbFawn.setText("Fawn");
        jpanelAdd2.add(cbFawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, -1, -1));

        cbTan.setText("Tan");
        jpanelAdd2.add(cbTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, -1, -1));

        cbChocolate.setText("Chocolate");
        cbChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChocolateActionPerformed(evt);
            }
        });
        jpanelAdd2.add(cbChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        cbBlue.setText("Blue");
        jpanelAdd2.add(cbBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        cbWhite.setText("White");
        jpanelAdd2.add(cbWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        cbSesame.setText("Sesame");
        jpanelAdd2.add(cbSesame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));

        cbRed.setText("Red");
        jpanelAdd2.add(cbRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, -1));
        jpanelAdd2.add(spinnerHeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 73, -1));

        jLabel7.setText("TO");
        jpanelAdd2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 178, -1, -1));

        comboBox_Add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Green", "Blue", "Hazel", "Brown", "Others", " " }));
        jpanelAdd2.add(comboBox_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));
        jpanelAdd2.add(spinnerLongevity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 73, -1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jpanelAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jpanelAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel8.setBackground(new java.awt.Color(56, 38, 36));

        jPanel9.setBackground(new java.awt.Color(188, 210, 224));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setBackground(new java.awt.Color(60, 63, 61));
        btnBack2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("<<<BACK");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel9.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 140, 30));

        tfTraits_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTraits_UpdateActionPerformed(evt);
            }
        });
        jPanel9.add(tfTraits_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 162, -1));

        tfOrigin_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrigin_UpdateActionPerformed(evt);
            }
        });
        jPanel9.add(tfOrigin_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 132, 162, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("S.No");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 57, 54, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Longevity");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Common Health Problems");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 150, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Height (in)");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 178, 65, -1));

        tfSnumber_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnumber_UpdateActionPerformed(evt);
            }
        });
        jPanel9.add(tfSnumber_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 54, 162, -1));
        jPanel9.add(tfHealthProblem_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 162, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Breed");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 95, 54, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Character Traits");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Obey%");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 54, -1));
        jPanel9.add(tfBreed_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 92, 162, -1));

        btnUpdate2.setBackground(new java.awt.Color(23, 35, 52));
        btnUpdate2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate2.setText("UPDATE");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        jPanel9.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 140, 29));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Eye Color");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 54, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Country of Origin");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 135, -1, -1));

        spinnerObey_Update.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        jPanel9.add(spinnerObey_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 162, -1));
        jPanel9.add(spinnerLongevity2_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 72, -1));
        jPanel9.add(spinnerLongevity1_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 73, -1));

        jLabel4.setText("TO");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 30, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Fur Color");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 70, -1));

        cbYellow_Update.setText("Yellow");
        cbYellow_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYellow_UpdateActionPerformed(evt);
            }
        });
        jPanel9.add(cbYellow_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        cbBlack_Update.setText("Black");
        jPanel9.add(cbBlack_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));

        cbGolden_Update.setText("Golden");
        jPanel9.add(cbGolden_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        cbFawn_Update.setText("Fawn");
        jPanel9.add(cbFawn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, -1, -1));

        cbTan_Update.setText("Tan");
        jPanel9.add(cbTan_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, -1, -1));

        cbChocolate_Update.setText("Chocolate");
        cbChocolate_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChocolate_UpdateActionPerformed(evt);
            }
        });
        jPanel9.add(cbChocolate_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        cbBlue_Update.setText("Blue");
        jPanel9.add(cbBlue_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        cbWhite_Update.setText("White");
        jPanel9.add(cbWhite_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        cbSesame_Update.setText("Sesame");
        jPanel9.add(cbSesame_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));

        cbRed_Update.setText("Red");
        jPanel9.add(cbRed_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, -1));

        comboBox_Update.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Green", "Blue", "Hazel", "Brown", "Others", " " }));
        jPanel9.add(comboBox_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));
        jPanel9.add(spinnerHeight1_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 175, 73, -1));

        jLabel8.setText("TO");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 178, -1, -1));
        jPanel9.add(spinnerHeight2_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 175, 72, -1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -43, -1, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        int currentRow = tblPetpulse.getSelectedRow();

        String id = tblPetpulse.getValueAt(currentRow, 0).toString();

        tfSnumber_Update.setText(tblPetpulse.getValueAt(currentRow, 0).toString());

        tfBreed_Update.setText(tblPetpulse.getValueAt(currentRow, 1).toString());

        tfOrigin_Update.setText(tblPetpulse.getValueAt(currentRow, 2).toString());

        String fur = tblPetpulse.getValueAt(currentRow, 3).toString();
        String[] furarr = fur.split(",");
        Component[] components = jPanel9.getComponents();
        for (String furr : furarr) {
            for (Component component : components) {
                if (component instanceof JCheckBox) {
                    JCheckBox checkbox = (JCheckBox) component;
                    if (checkbox.getText().equals(furr)) {
                        checkbox.setSelected(true);
                    }
                }
            }
        }

        String[] values = (tblPetpulse.getValueAt(currentRow, 4).toString()).split("-");
        int minheight_Update = Integer.parseInt(values[0].trim());
        int maxheight_Update = Integer.parseInt(values[1].trim());
        spinnerHeight1_Update.setValue(minheight_Update);
        spinnerHeight2_Update.setValue(maxheight_Update);

        comboBox_Update.setSelectedItem(tblPetpulse.getValueAt(currentRow, 5).toString());

        String[] values1 = (tblPetpulse.getValueAt(currentRow, 6).toString()).split("-");
        int minlongevity_Update = Integer.parseInt(values1[0].trim());
        int maxlongevity_Update = Integer.parseInt(values1[1].trim());
        spinnerLongevity1_Update.setValue(minlongevity_Update);
        spinnerLongevity2_Update.setValue(maxlongevity_Update);

        tfTraits_Update.setText(tblPetpulse.getValueAt(currentRow, 7).toString());

        tfHealthProblem_Update.setText(tblPetpulse.getValueAt(currentRow, 8).toString());

        spinnerObey_Update.setValue(Integer.parseInt(tblPetpulse.getValueAt(currentRow, 9).toString()));

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPetpulse.getModel();
        if (tblPetpulse.getSelectedRow() != -1) {
            model.removeRow(tblPetpulse.getSelectedRow());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void tfTraits_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTraits_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTraits_UpdateActionPerformed

    private void tfOrigin_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrigin_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrigin_UpdateActionPerformed

    private void tfSnumber_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnumber_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnumber_UpdateActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        int currentRow = tblPetpulse.getSelectedRow();
        tblPetpulse.setValueAt(tfSnumber_Update.getText(), currentRow, 0);

        tblPetpulse.setValueAt(tfBreed_Update.getText(), currentRow, 1);

        tblPetpulse.setValueAt(tfOrigin_Update.getText(), currentRow, 2);

        Component[] components = jPanel9.getComponents();
        ArrayList<String> fur = new ArrayList<>();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkbox = (JCheckBox) component;
                if (checkbox.isSelected()) {
                    fur.add(checkbox.getText());
                }
            }
        }
        String furs = String.join(", ", fur);
        tblPetpulse.setValueAt(furs, currentRow, 3);

        int minHeight = Integer.parseInt(spinnerHeight1_Update.getValue().toString());
        int maxHeight = Integer.parseInt(spinnerHeight2_Update.getValue().toString());
        String height = minHeight + "-" + maxHeight;
        tblPetpulse.setValueAt(height, currentRow, 4);

        tblPetpulse.setValueAt(comboBox_Update.getSelectedItem(), currentRow, 5);

        int minLongevity = Integer.parseInt(spinnerLongevity2_Update.getValue().toString());
        int maxLongevity = Integer.parseInt(spinnerLongevity2_Update.getValue().toString());
        String longevity = minLongevity + "-" + maxLongevity;
        tblPetpulse.setValueAt(longevity, currentRow, 6);

        tblPetpulse.setValueAt(tfTraits_Update.getText(), currentRow, 7);

        tblPetpulse.setValueAt(tfHealthProblem_Update.getText(), currentRow, 8);

        tblPetpulse.setValueAt(Integer.parseInt(spinnerObey_Update.getValue().toString()), currentRow, 9);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void cbYellow_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYellow_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYellow_UpdateActionPerformed

    private void cbChocolate_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChocolate_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChocolate_UpdateActionPerformed

    private void cbChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChocolateActionPerformed

    private void cbYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYellowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYellowActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
       try{
             snumber = Integer.parseInt(tfSnumber.getText());
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(jpanelAdd2, StringUtils.INTEGER_MESSAGE);
       }
       
       if ((tfBreed.getText()).matches("^[a-zA-Z\\s]+$")){
       String breed = tfBreed.getText();
       }else{
          JOptionPane.showMessageDialog(jpanelAdd2, StringUtils.STRING_MESSAGE);
       }
        
       
        String origin = tfOrigin.getText(); 
        
        ArrayList<String> furColors = new ArrayList<>();
        Component[] components = jpanelAdd2.getComponents();
        for (Component component : components) {
            if(component instanceof JCheckBox) {
                JCheckBox checkbox = (JCheckBox) component;
                if (checkbox.isSelected()) {
                    furColors.add(checkbox.getText());
                }
            }
        }
        String checkedFurColors = String.join(",", furColors);
        int minHeight = Integer.parseInt(spinnerHeight1.getValue().toString());
        int maxHeight = Integer.parseInt(spinnerHeight2.getValue().toString());
        String height = minHeight + "-" + maxHeight;
        String eyeColor = comboBox_Add.getSelectedItem().toString();
        int minLongevity = Integer.parseInt(spinnerLongevity2.getValue().toString());
        int maxLongevity = Integer.parseInt(spinnerLongevity2.getValue().toString());
        String longevity = minLongevity + "-" + maxLongevity;
        String characterTraits = tfTraits.getText();
        String healthProblem = tfHealthProblem.getText();
        int obey = Integer.parseInt(spinnerObey.getValue().toString());

        DefaultTableModel tableModel = (DefaultTableModel) tblPetpulse.getModel();
        tableModel.addRow(new Object[]{snumber, breed, origin, checkedFurColors, height, eyeColor, longevity, characterTraits, healthProblem, obey});
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void tfSnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnumberActionPerformed

    private void tfOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOriginActionPerformed

    private void tfTraitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTraitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTraitsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petpulse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petpulse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petpulse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petpulse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petpulse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JCheckBox cbBlack;
    private javax.swing.JCheckBox cbBlack_Update;
    private javax.swing.JCheckBox cbBlue;
    private javax.swing.JCheckBox cbBlue_Update;
    private javax.swing.JCheckBox cbChocolate;
    private javax.swing.JCheckBox cbChocolate_Update;
    private javax.swing.JCheckBox cbFawn;
    private javax.swing.JCheckBox cbFawn_Update;
    private javax.swing.JCheckBox cbGolden;
    private javax.swing.JCheckBox cbGolden_Update;
    private javax.swing.JCheckBox cbRed;
    private javax.swing.JCheckBox cbRed_Update;
    private javax.swing.JCheckBox cbSesame;
    private javax.swing.JCheckBox cbSesame_Update;
    private javax.swing.JCheckBox cbTan;
    private javax.swing.JCheckBox cbTan_Update;
    private javax.swing.JCheckBox cbWhite;
    private javax.swing.JCheckBox cbWhite_Update;
    private javax.swing.JCheckBox cbYellow;
    private javax.swing.JCheckBox cbYellow_Update;
    private javax.swing.JComboBox<String> comboBox_Add;
    private javax.swing.JComboBox<String> comboBox_Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpanelAdd2;
    private javax.swing.JSpinner spinnerHeight1;
    private javax.swing.JSpinner spinnerHeight1_Update;
    private javax.swing.JSpinner spinnerHeight2;
    private javax.swing.JSpinner spinnerHeight2_Update;
    private javax.swing.JSpinner spinnerLongevity1;
    private javax.swing.JSpinner spinnerLongevity1_Update;
    private javax.swing.JSpinner spinnerLongevity2;
    private javax.swing.JSpinner spinnerLongevity2_Update;
    private javax.swing.JSpinner spinnerObey;
    private javax.swing.JSpinner spinnerObey_Update;
    private javax.swing.JTable tblPetpulse;
    private javax.swing.JTextField tfBreed;
    private javax.swing.JTextField tfBreed_Update;
    private javax.swing.JTextField tfHealthProblem;
    private javax.swing.JTextField tfHealthProblem_Update;
    private javax.swing.JTextField tfOrigin;
    private javax.swing.JTextField tfOrigin_Update;
    private javax.swing.JTextField tfSnumber;
    private javax.swing.JTextField tfSnumber_Update;
    private javax.swing.JTextField tfTraits;
    private javax.swing.JTextField tfTraits_Update;
    // End of variables declaration//GEN-END:variables
}
